# Generated by Django 3.2.10 on 2021-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('Image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('Text', models.TextField(verbose_name='Содержание')),
                ('Date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
