# Generated by Django 3.2.10 on 2021-12-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Районы',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='doc',
            name='Description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='File',
            field=models.FileField(upload_to='file/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Prject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('Image', models.ImageField(upload_to='prject/', verbose_name='Изображение')),
                ('Text', models.TextField(verbose_name='Содержание')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
