# Generated by Django 3.2.10 on 2021-12-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211219_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prject',
            new_name='Project',
        ),
    ]
